export const mockCourses = [
  {
    id: "1",
    title: "Complete React Development",
    description:
      "Master React from fundamentals to advanced concepts including hooks, context, and testing.",
    instructor: "Sarah Johnson",
    category: "Programming",
    difficulty: "intermediate",
    duration: "24 hours",
    rating: 4.8,
    enrolledStudents: 1250,
    price: 89.99,
    image: "/placeholder.svg",
    prerequisites: ["Basic JavaScript", "HTML/CSS"],
    modules: [
      {
        id: "m1",
        title: "React Fundamentals",
        isCompleted: true,
        lessons: [
          {
            id: "l1",
            title: "Introduction to React",
            type: "video",
            duration: "15 min",
            videoUrl: "https://www.youtube.com/embed/dGcsHMXbSOA",
            isCompleted: true,
          },
          {
            id: "l2",
            title: "Components and JSX",
            type: "video",
            duration: "20 min",
            videoUrl: "https://www.youtube.com/embed/dGcsHMXbSOA",
            isCompleted: true,
          },
          {
            id: "l3",
            title: "React Basics Quiz",
            type: "quiz",
            duration: "10 min",
            isCompleted: false,
            quiz: {
              id: "q1",
              questions: [
                {
                  id: "q1-1",
                  type: "multiple-choice",
                  question: "What does JSX stand for?",
                  options: [
                    "JavaScript XML",
                    "JavaScript Extension",
                    "Java Syntax Extension",
                    "Just Syntax Extension",
                  ],
                  correctAnswer: 0,
                  explanation:
                    "JSX stands for JavaScript XML and allows you to write HTML-like syntax in JavaScript.",
                },
              ],
            },
          },
        ],
      },
      {
        id: "m2",
        title: "State and Props",
        isCompleted: false,
        lessons: [
          {
            id: "l4",
            title: "Understanding State",
            type: "video",
            duration: "18 min",
            videoUrl: "https://www.youtube.com/embed/dGcsHMXbSOA",
            isCompleted: false,
          },
          {
            id: "l5",
            title: "Props Deep Dive",
            type: "video",
            duration: "22 min",
            videoUrl: "https://www.youtube.com/embed/dGcsHMXbSOA",
            isCompleted: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u1",
        userName: "John Doe",
        rating: 5,
        comment: "Excellent course! Very comprehensive and well-structured.",
        date: "2024-01-15",
      },
    ],
  },
  {
    id: "2",
    title: "Fullstack Web Development with MERN",
    description:
      "Build dynamic web apps using MongoDB, Express, React, and Node.js.",
    instructor: "Michael Smith",
    category: "Web Development",
    difficulty: "advanced",
    duration: "30 hours",
    rating: 4.7,
    enrolledStudents: 980,
    price: 109.99,
    image: "/placeholder.svg",
    prerequisites: ["JavaScript", "Basic React", "Node.js"],
    modules: [
      {
        id: "m1",
        title: "MERN Overview",
        isCompleted: true,
        lessons: [
          {
            id: "l1",
            title: "What is MERN Stack?",
            type: "video",
            duration: "12 min",
            videoUrl: "https://www.youtube.com/embed/Ke90Tje7VS0",
            isCompleted: true,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u2",
        userName: "Priya Sharma",
        rating: 4.5,
        comment: "Very insightful and practical course.",
        date: "2024-02-10",
      },
    ],
  },
  {
    id: "3",
    title: "Intro to Python Programming",
    description:
      "Learn Python from scratch. Ideal for beginners with no prior experience.",
    instructor: "Emily Davis",
    category: "Programming",
    difficulty: "beginner",
    duration: "15 hours",
    rating: 4.6,
    enrolledStudents: 3200,
    price: 49.99,
    image: "/placeholder.svg",
    prerequisites: ["None"],
    modules: [
      {
        id: "m1",
        title: "Getting Started",
        isCompleted: true,
        lessons: [
          {
            id: "l1",
            title: "Installing Python",
            type: "video",
            duration: "10 min",
            videoUrl: "https://www.youtube.com/embed/rfscVS0vtbw",
            isCompleted: true,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u3",
        userName: "Rajesh Karki",
        rating: 5,
        comment: "Perfect for beginners. Easy to follow.",
        date: "2024-03-05",
      },
    ],
  },
  {
    id: "4",
    title: "UI/UX Design Basics",
    description:
      "Understand the fundamentals of UI/UX design with practical tools and tips.",
    instructor: "Laura Chen",
    category: "Design",
    difficulty: "beginner",
    duration: "10 hours",
    rating: 4.3,
    enrolledStudents: 870,
    price: 59.99,
    image: "/placeholder.svg",
    prerequisites: ["Basic computer skills"],
    modules: [
      {
        id: "m1",
        title: "Introduction to UI/UX",
        isCompleted: false,
        lessons: [
          {
            id: "l1",
            title: "Design Thinking",
            type: "video",
            duration: "25 min",
            videoUrl: "https://www.youtube.com/embed/_OcozA0MDrM",
            isCompleted: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u4",
        userName: "Sneha Thapa",
        rating: 4,
        comment: "Good introduction to design concepts.",
        date: "2024-04-01",
      },
    ],
  },
  {
    id: "5",
    title: "Data Structures and Algorithms in Java",
    description: "Deep dive into DSA with Java to crack technical interviews.",
    instructor: "Robert Martin",
    category: "Computer Science",
    difficulty: "advanced",
    duration: "35 hours",
    rating: 4.9,
    enrolledStudents: 2100,
    price: 99.99,
    image: "/placeholder.svg",
    prerequisites: ["Basic Java"],
    modules: [
      {
        id: "m1",
        title: "Arrays and Strings",
        isCompleted: false,
        lessons: [
          {
            id: "l1",
            title: "Array Basics",
            type: "video",
            duration: "17 min",
            videoUrl: "https://www.youtube.com/embed/Wo8z3TFd3nw",
            isCompleted: false,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u5",
        userName: "Kishor Neupane",
        rating: 5,
        comment: "Very helpful for interview prep.",
        date: "2024-05-12",
      },
    ],
  },
  {
    id: "6",
    title: "Mastering SQL for Data Analysis",
    description:
      "Write powerful SQL queries for extracting and analyzing data.",
    instructor: "Aisha Patel",
    category: "Data Analysis",
    difficulty: "intermediate",
    duration: "20 hours",
    rating: 4.7,
    enrolledStudents: 1550,
    price: 79.99,
    image: "/placeholder.svg",
    prerequisites: ["Basic Excel or data handling"],
    modules: [
      {
        id: "m1",
        title: "SQL Fundamentals",
        isCompleted: true,
        lessons: [
          {
            id: "l1",
            title: "SELECT Queries",
            type: "video",
            duration: "20 min",
            videoUrl: "https://www.youtube.com/embed/9Pzj7Aj25lw",
            isCompleted: true,
          },
        ],
      },
    ],
    reviews: [
      {
        id: "r1",
        userId: "u6",
        userName: "Nisha Rai",
        rating: 4.8,
        comment: "Great for aspiring data analysts.",
        date: "2024-06-01",
      },
    ],
  },
];
